name: 🐞 Bug report
description: Report a bug or documentation issue to help us improve
title: "[BUG]"
labels: [bug, needs-triage]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues.
          required: true
  - type: dropdown
    id: area
    attributes:
      label: Issue Type
      description: Choose the type of issue you'd like to report.
      options:
        - Bug Report
        - Documentation Issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Descripton
      description: Provide a clear and concise description of the problem. Describe where it appears, when it occurred, and what it affects.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expect to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: |
        Optionally, add screenshots to help explain your problem.

        Tip: To attach images or files, click this area to highlight it and then drag files in.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context, like links or references about the problem. Anything that gives us more context about the issue you are encountering.

        Tip: To attach images or files, click this area to highlight it and then drag files in.
    validations:
      required: false
