name: 💡Feature request
description: Suggest an idea for this project
title: "[FEATURE]"
labels: [enhancement, pending-decision]
body:
  - type: dropdown
    attributes:
      label: Improvement Area
      description: Choose the area that you want to see improved.
      options:
        - Samples
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: area
    attributes:
      label: Is your feature request related to a problem?
      description: Provide a clear and concise description of what the problem is. For example, I am always frustrated when ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired Solution
      description: A clear and concise description of the solution you would like to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you have considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context like links or references about the problem here. Anything that will give us more context about the issue you are encountering!

        Tip: To attach images or files, click this area to highlight it and then drag files in.
    validations:
      required: false
