
name: Set default values to PR
# Add the PR to the central project (status in project is set via workflow in project)
# Add the creator of the PR as assignee
# Add the next available milestone to the PR

on:
  pull_request:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  set-default-values:
    runs-on: ubuntu-latest
    steps:
      - name: Add creator as assignee
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{github.repository}}/issues/${{github.event.number}}/assignees \
           -f "assignees[]=${{github.actor}}"

      - name: Set default labels
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/github-script@v8
        env:
          TITLE: ${{ github.event.pull_request.title }}
        with:
          script: |
            const title = process.env.TITLE;

            let defaultLabels = [];
            if (title.startsWith("feat:")) {
              defaultLabels.push("enhancement");
            } else if (title.startsWith("fix:")) {
              defaultLabels.push("bug");
            } else if (title.startsWith("docs:")) {
              defaultLabels.push("documentation");
            } else if (title.startsWith("test:")) {
              defaultLabels.push("test setup");
            } else if (title.startsWith("refactor:")) {
              defaultLabels.push("refactoring");
            } else {
              defaultLabels.push("internal");
            }

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: defaultLabels
            });
